In [1]:
from langchain_chroma import Chroma


In [2]:
# create embedding model object
import torch

In [3]:
if torch.backends.mps.is_available():
    mps_device = torch.device('mps')
    x = torch.ones(5, device=mps_device)
    print(x)
else:
    print("device mps not found")

tensor([1., 1., 1., 1., 1.], device='mps:0')


In [4]:
# call indobert transformers
from transformers import BertTokenizer, AutoModel

tokenizer = BertTokenizer.from_pretrained("indobenchmark/indobert-base-p1")
model = AutoModel.from_pretrained("indobenchmark/indobert-base-p1")

/Users/a/Programming/Langchain-Project/my-env/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [5]:
x = torch.LongTensor(tokenizer.encode('nama saya adalah romi')).view(1,-1)
print(x, model(x)[0].sum())

tensor([[    2,   712,   209,   154,  3610, 30356,     3]]) tensor(-0.0870, grad_fn=<SumBackward0>)


In [6]:
# test embedding model dengan indobert

x = torch.LongTensor(tokenizer.encode("")).view(1, -1)

In [7]:
print(x, model(x)[0].sum())

tensor([[2, 3]]) tensor(0.1667, grad_fn=<SumBackward0>)


In [8]:
# save data vector with chroma on memory not persistance and this will be not save on disk

vector_store = Chroma(
    collection_name="test-collection",
    embedding_function=tokenizer,
)

In [9]:
# untuk berinteraksi dengan chromadb, kita bisa menggunkana ChromaClient (ini adalah chroma client in memory bukan persistance)

import chromadb

client = chromadb.Client()

In [10]:
# setelah client berhasil dibuat, kemudian connect to server

client = chromadb.HttpClient()

### Ternyata untuk menggunakan chromadb, kita wajib menginstall chromadb diluar langchain, dan setiap ingin menjalankan harus menggunakan perintah chroma run (chroma akan jalan pada port 8000 secara default)

### Jadi setelah chromadb client berhasil dibuat dan telah berhasil connect ke chromadb server, selanjutnya adalah membuat collection sebagai tempat untuk menyimpan vector atau vector store, document, also any additional data

In [18]:
collection = client.get_or_create_collection(name="test-collection")

In [19]:
collection_list = client.list_collections()

In [20]:
for instance in collection_list:
    print(instance)

Collection(name=test-collection)


In [21]:
collection.add(ids=["1", "2", "3"], documents=["a", "b", "c"])

/Users/a/.cache/chroma/onnx_models/all-MiniLM-L6-v2/onnx.tar.gz: 100%|██████████| 79.3M/79.3M [01:10<00:00, 1.17MiB/s]


In [ ]:
# menambahkan document kedalam collection (test-collection dengan menggunakan vector store yang telah kita buat dengan lanchain)


In [ ]:
from langchain_core.documents import Document

document_4 = Document(
    page_content="Robbers broke into the city bank and stole $1 million in cash.",
    metadata={"source": "news"},
    id=4,
)